//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlArriendos.ServicioLibros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EJEMPLAR", Namespace="http://serviciowebareainternet.dim.cl/")]
    [System.SerializableAttribute()]
    public partial class EJEMPLAR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CODLIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITLIBField;
        
        private decimal EDILIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AUTLIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UBILIBField;
        
        private decimal ULTLECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISPONField;
        
        private System.Nullable<System.DateTime> FECPREField;
        
        private System.Nullable<System.DateTime> FECDEVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal CODLIB {
            get {
                return this.CODLIBField;
            }
            set {
                if ((this.CODLIBField.Equals(value) != true)) {
                    this.CODLIBField = value;
                    this.RaisePropertyChanged("CODLIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TITLIB {
            get {
                return this.TITLIBField;
            }
            set {
                if ((object.ReferenceEquals(this.TITLIBField, value) != true)) {
                    this.TITLIBField = value;
                    this.RaisePropertyChanged("TITLIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal EDILIB {
            get {
                return this.EDILIBField;
            }
            set {
                if ((this.EDILIBField.Equals(value) != true)) {
                    this.EDILIBField = value;
                    this.RaisePropertyChanged("EDILIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AUTLIB {
            get {
                return this.AUTLIBField;
            }
            set {
                if ((object.ReferenceEquals(this.AUTLIBField, value) != true)) {
                    this.AUTLIBField = value;
                    this.RaisePropertyChanged("AUTLIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UBILIB {
            get {
                return this.UBILIBField;
            }
            set {
                if ((object.ReferenceEquals(this.UBILIBField, value) != true)) {
                    this.UBILIBField = value;
                    this.RaisePropertyChanged("UBILIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal ULTLEC {
            get {
                return this.ULTLECField;
            }
            set {
                if ((this.ULTLECField.Equals(value) != true)) {
                    this.ULTLECField = value;
                    this.RaisePropertyChanged("ULTLEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DISPON {
            get {
                return this.DISPONField;
            }
            set {
                if ((object.ReferenceEquals(this.DISPONField, value) != true)) {
                    this.DISPONField = value;
                    this.RaisePropertyChanged("DISPON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> FECPRE {
            get {
                return this.FECPREField;
            }
            set {
                if ((this.FECPREField.Equals(value) != true)) {
                    this.FECPREField = value;
                    this.RaisePropertyChanged("FECPRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> FECDEV {
            get {
                return this.FECDEVField;
            }
            set {
                if ((this.FECDEVField.Equals(value) != true)) {
                    this.FECDEVField = value;
                    this.RaisePropertyChanged("FECDEV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/", ConfigurationName="ServicioLibros.DemoSoap")]
    public interface DemoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/AgregaLibro", ReplyAction="*")]
        ControlArriendos.ServicioLibros.AgregaLibroResponse AgregaLibro(ControlArriendos.ServicioLibros.AgregaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/AgregaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.AgregaLibroResponse> AgregaLibroAsync(ControlArriendos.ServicioLibros.AgregaLibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaEjemplarResult del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplar", ReplyAction="*")]
        ControlArriendos.ServicioLibros.ListaEjemplarResponse ListaEjemplar(ControlArriendos.ServicioLibros.ListaEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplar", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarResponse> ListaEjemplarAsync(ControlArriendos.ServicioLibros.ListaEjemplarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaEjemplarPorCodigoResult del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplarPorCodigo", ReplyAction="*")]
        ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse ListaEjemplarPorCodigo(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplarPorCodigo", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse> ListaEjemplarPorCodigoAsync(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaEjemplarDelimitadoResult del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplarDelimitado", ReplyAction="*")]
        ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse ListaEjemplarDelimitado(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListaEjemplarDelimitado", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse> ListaEjemplarDelimitadoAsync(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Busqueda del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListEjemplarPorTituloORAutor", ReplyAction="*")]
        ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse ListEjemplarPorTituloORAutor(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ListEjemplarPorTituloORAutor", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse> ListEjemplarPorTituloORAutorAsync(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://serviciowebareainternet.dim.cl/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ModificaLibro", ReplyAction="*")]
        ControlArriendos.ServicioLibros.ModificaLibroResponse ModificaLibro(ControlArriendos.ServicioLibros.ModificaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/ModificaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ModificaLibroResponse> ModificaLibroAsync(ControlArriendos.ServicioLibros.ModificaLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/EliminaLibro", ReplyAction="*")]
        int EliminaLibro(decimal codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciowebareainternet.dim.cl/EliminaLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminaLibroAsync(decimal codigo);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregaLibro", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.AgregaLibroRequestBody Body;
        
        public AgregaLibroRequest() {
        }
        
        public AgregaLibroRequest(ControlArriendos.ServicioLibros.AgregaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class AgregaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string autor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int editor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ubicacion;
        
        public AgregaLibroRequestBody() {
        }
        
        public AgregaLibroRequestBody(string titulo, string autor, int editor, string ubicacion) {
            this.titulo = titulo;
            this.autor = autor;
            this.editor = editor;
            this.ubicacion = ubicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregaLibroResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.AgregaLibroResponseBody Body;
        
        public AgregaLibroResponse() {
        }
        
        public AgregaLibroResponse(ControlArriendos.ServicioLibros.AgregaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class AgregaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregaLibroResult;
        
        public AgregaLibroResponseBody() {
        }
        
        public AgregaLibroResponseBody(bool AgregaLibroResult) {
            this.AgregaLibroResult = AgregaLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplar", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarRequestBody Body;
        
        public ListaEjemplarRequest() {
        }
        
        public ListaEjemplarRequest(ControlArriendos.ServicioLibros.ListaEjemplarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaEjemplarRequestBody {
        
        public ListaEjemplarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplarResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarResponseBody Body;
        
        public ListaEjemplarResponse() {
        }
        
        public ListaEjemplarResponse(ControlArriendos.ServicioLibros.ListaEjemplarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListaEjemplarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarResult;
        
        public ListaEjemplarResponseBody() {
        }
        
        public ListaEjemplarResponseBody(ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarResult) {
            this.ListaEjemplarResult = ListaEjemplarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarPorCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplarPorCodigo", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequestBody Body;
        
        public ListaEjemplarPorCodigoRequest() {
        }
        
        public ListaEjemplarPorCodigoRequest(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListaEjemplarPorCodigoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal codigo;
        
        public ListaEjemplarPorCodigoRequestBody() {
        }
        
        public ListaEjemplarPorCodigoRequestBody(decimal codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarPorCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplarPorCodigoResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponseBody Body;
        
        public ListaEjemplarPorCodigoResponse() {
        }
        
        public ListaEjemplarPorCodigoResponse(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListaEjemplarPorCodigoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarPorCodigoResult;
        
        public ListaEjemplarPorCodigoResponseBody() {
        }
        
        public ListaEjemplarPorCodigoResponseBody(ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarPorCodigoResult) {
            this.ListaEjemplarPorCodigoResult = ListaEjemplarPorCodigoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarDelimitadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplarDelimitado", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequestBody Body;
        
        public ListaEjemplarDelimitadoRequest() {
        }
        
        public ListaEjemplarDelimitadoRequest(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListaEjemplarDelimitadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int delimitador;
        
        public ListaEjemplarDelimitadoRequestBody() {
        }
        
        public ListaEjemplarDelimitadoRequestBody(int delimitador) {
            this.delimitador = delimitador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaEjemplarDelimitadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaEjemplarDelimitadoResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponseBody Body;
        
        public ListaEjemplarDelimitadoResponse() {
        }
        
        public ListaEjemplarDelimitadoResponse(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListaEjemplarDelimitadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarDelimitadoResult;
        
        public ListaEjemplarDelimitadoResponseBody() {
        }
        
        public ListaEjemplarDelimitadoResponseBody(ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarDelimitadoResult) {
            this.ListaEjemplarDelimitadoResult = ListaEjemplarDelimitadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEjemplarPorTituloORAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEjemplarPorTituloORAutor", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequestBody Body;
        
        public ListEjemplarPorTituloORAutorRequest() {
        }
        
        public ListEjemplarPorTituloORAutorRequest(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListEjemplarPorTituloORAutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Busqueda;
        
        public ListEjemplarPorTituloORAutorRequestBody() {
        }
        
        public ListEjemplarPorTituloORAutorRequestBody(string Busqueda) {
            this.Busqueda = Busqueda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEjemplarPorTituloORAutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEjemplarPorTituloORAutorResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponseBody Body;
        
        public ListEjemplarPorTituloORAutorResponse() {
        }
        
        public ListEjemplarPorTituloORAutorResponse(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ListEjemplarPorTituloORAutorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListEjemplarPorTituloORAutorResult;
        
        public ListEjemplarPorTituloORAutorResponseBody() {
        }
        
        public ListEjemplarPorTituloORAutorResponseBody(ControlArriendos.ServicioLibros.EJEMPLAR[] ListEjemplarPorTituloORAutorResult) {
            this.ListEjemplarPorTituloORAutorResult = ListEjemplarPorTituloORAutorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaLibro", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ModificaLibroRequestBody Body;
        
        public ModificaLibroRequest() {
        }
        
        public ModificaLibroRequest(ControlArriendos.ServicioLibros.ModificaLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ModificaLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int editor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ubicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dispon;
        
        public ModificaLibroRequestBody() {
        }
        
        public ModificaLibroRequestBody(decimal codigo, string titulo, string autor, int editor, string ubicacion, string dispon) {
            this.codigo = codigo;
            this.titulo = titulo;
            this.autor = autor;
            this.editor = editor;
            this.ubicacion = ubicacion;
            this.dispon = dispon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaLibroResponse", Namespace="http://serviciowebareainternet.dim.cl/", Order=0)]
        public ControlArriendos.ServicioLibros.ModificaLibroResponseBody Body;
        
        public ModificaLibroResponse() {
        }
        
        public ModificaLibroResponse(ControlArriendos.ServicioLibros.ModificaLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://serviciowebareainternet.dim.cl/")]
    public partial class ModificaLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ModificaLibroResult;
        
        public ModificaLibroResponseBody() {
        }
        
        public ModificaLibroResponseBody(int ModificaLibroResult) {
            this.ModificaLibroResult = ModificaLibroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DemoSoapChannel : ControlArriendos.ServicioLibros.DemoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoSoapClient : System.ServiceModel.ClientBase<ControlArriendos.ServicioLibros.DemoSoap>, ControlArriendos.ServicioLibros.DemoSoap {
        
        public DemoSoapClient() {
        }
        
        public DemoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.AgregaLibroResponse ControlArriendos.ServicioLibros.DemoSoap.AgregaLibro(ControlArriendos.ServicioLibros.AgregaLibroRequest request) {
            return base.Channel.AgregaLibro(request);
        }
        
        public bool AgregaLibro(string titulo, string autor, int editor, string ubicacion) {
            ControlArriendos.ServicioLibros.AgregaLibroRequest inValue = new ControlArriendos.ServicioLibros.AgregaLibroRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.AgregaLibroRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.autor = autor;
            inValue.Body.editor = editor;
            inValue.Body.ubicacion = ubicacion;
            ControlArriendos.ServicioLibros.AgregaLibroResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).AgregaLibro(inValue);
            return retVal.Body.AgregaLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.AgregaLibroResponse> ControlArriendos.ServicioLibros.DemoSoap.AgregaLibroAsync(ControlArriendos.ServicioLibros.AgregaLibroRequest request) {
            return base.Channel.AgregaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.AgregaLibroResponse> AgregaLibroAsync(string titulo, string autor, int editor, string ubicacion) {
            ControlArriendos.ServicioLibros.AgregaLibroRequest inValue = new ControlArriendos.ServicioLibros.AgregaLibroRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.AgregaLibroRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.autor = autor;
            inValue.Body.editor = editor;
            inValue.Body.ubicacion = ubicacion;
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).AgregaLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.ListaEjemplarResponse ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplar(ControlArriendos.ServicioLibros.ListaEjemplarRequest request) {
            return base.Channel.ListaEjemplar(request);
        }
        
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplar() {
            ControlArriendos.ServicioLibros.ListaEjemplarRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarRequestBody();
            ControlArriendos.ServicioLibros.ListaEjemplarResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplar(inValue);
            return retVal.Body.ListaEjemplarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarResponse> ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplarAsync(ControlArriendos.ServicioLibros.ListaEjemplarRequest request) {
            return base.Channel.ListaEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarResponse> ListaEjemplarAsync() {
            ControlArriendos.ServicioLibros.ListaEjemplarRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarRequestBody();
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplarPorCodigo(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest request) {
            return base.Channel.ListaEjemplarPorCodigo(request);
        }
        
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarPorCodigo(decimal codigo) {
            ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequestBody();
            inValue.Body.codigo = codigo;
            ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplarPorCodigo(inValue);
            return retVal.Body.ListaEjemplarPorCodigoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse> ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplarPorCodigoAsync(ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest request) {
            return base.Channel.ListaEjemplarPorCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoResponse> ListaEjemplarPorCodigoAsync(decimal codigo) {
            ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarPorCodigoRequestBody();
            inValue.Body.codigo = codigo;
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplarPorCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplarDelimitado(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest request) {
            return base.Channel.ListaEjemplarDelimitado(request);
        }
        
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListaEjemplarDelimitado(int delimitador) {
            ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequestBody();
            inValue.Body.delimitador = delimitador;
            ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplarDelimitado(inValue);
            return retVal.Body.ListaEjemplarDelimitadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse> ControlArriendos.ServicioLibros.DemoSoap.ListaEjemplarDelimitadoAsync(ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest request) {
            return base.Channel.ListaEjemplarDelimitadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoResponse> ListaEjemplarDelimitadoAsync(int delimitador) {
            ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest inValue = new ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListaEjemplarDelimitadoRequestBody();
            inValue.Body.delimitador = delimitador;
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListaEjemplarDelimitadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse ControlArriendos.ServicioLibros.DemoSoap.ListEjemplarPorTituloORAutor(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest request) {
            return base.Channel.ListEjemplarPorTituloORAutor(request);
        }
        
        public ControlArriendos.ServicioLibros.EJEMPLAR[] ListEjemplarPorTituloORAutor(string Busqueda) {
            ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest inValue = new ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequestBody();
            inValue.Body.Busqueda = Busqueda;
            ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListEjemplarPorTituloORAutor(inValue);
            return retVal.Body.ListEjemplarPorTituloORAutorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse> ControlArriendos.ServicioLibros.DemoSoap.ListEjemplarPorTituloORAutorAsync(ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest request) {
            return base.Channel.ListEjemplarPorTituloORAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorResponse> ListEjemplarPorTituloORAutorAsync(string Busqueda) {
            ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest inValue = new ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ListEjemplarPorTituloORAutorRequestBody();
            inValue.Body.Busqueda = Busqueda;
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ListEjemplarPorTituloORAutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlArriendos.ServicioLibros.ModificaLibroResponse ControlArriendos.ServicioLibros.DemoSoap.ModificaLibro(ControlArriendos.ServicioLibros.ModificaLibroRequest request) {
            return base.Channel.ModificaLibro(request);
        }
        
        public int ModificaLibro(decimal codigo, string titulo, string autor, int editor, string ubicacion, string dispon) {
            ControlArriendos.ServicioLibros.ModificaLibroRequest inValue = new ControlArriendos.ServicioLibros.ModificaLibroRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ModificaLibroRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.titulo = titulo;
            inValue.Body.autor = autor;
            inValue.Body.editor = editor;
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.dispon = dispon;
            ControlArriendos.ServicioLibros.ModificaLibroResponse retVal = ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ModificaLibro(inValue);
            return retVal.Body.ModificaLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ModificaLibroResponse> ControlArriendos.ServicioLibros.DemoSoap.ModificaLibroAsync(ControlArriendos.ServicioLibros.ModificaLibroRequest request) {
            return base.Channel.ModificaLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlArriendos.ServicioLibros.ModificaLibroResponse> ModificaLibroAsync(decimal codigo, string titulo, string autor, int editor, string ubicacion, string dispon) {
            ControlArriendos.ServicioLibros.ModificaLibroRequest inValue = new ControlArriendos.ServicioLibros.ModificaLibroRequest();
            inValue.Body = new ControlArriendos.ServicioLibros.ModificaLibroRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.titulo = titulo;
            inValue.Body.autor = autor;
            inValue.Body.editor = editor;
            inValue.Body.ubicacion = ubicacion;
            inValue.Body.dispon = dispon;
            return ((ControlArriendos.ServicioLibros.DemoSoap)(this)).ModificaLibroAsync(inValue);
        }
        
        public int EliminaLibro(decimal codigo) {
            return base.Channel.EliminaLibro(codigo);
        }
        
        public System.Threading.Tasks.Task<int> EliminaLibroAsync(decimal codigo) {
            return base.Channel.EliminaLibroAsync(codigo);
        }
    }
}
